<a href="https://colab.research.google.com/github/irabi111/TDSPROJ1/blob/main/tds_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
users = pd.read_csv('users.csv')
users.head()

,login,name,company,location,email,hireable,bio,public_repos,followers,following,created_at
0,mosh-hamedani,Mosh Hamedani,NaN,"Melbourne, Australia",NaN,False,I train software engineers that companies love...,27,12782,1,2013-09-12T04:38:33Z
1,TheCherno,Yan Chernikov,NaN,"Melbourne, Australia",NaN,False,NaN,35,11229,4,2012-02-26T08:39:00Z
2,haileys,Hailey Somerville,NaN,Naarm / Melbourne,hailey@hailey.lol,False,NaN,372,9392,104,2010-01-09T14:49:23Z
3,rstacruz,Rico Sta. Cruz,NaN,"Melbourne, AU",NaN,True,@rstacruz@hachyderm.io,562,6434,25,2009-04-16T09:46:24Z
4,jesseduffield,Jesse Duffield,NaN,Melbourne,jessedduffield@gmail.com,False,"Creator of lazygit, lazydocker, horcrux, and t...",60,4576,4,2014-08-15T09:18:18Z

In [ ]:
users['hireable'] = users['hireable'].fillna(False).astype(bool)

In [ ]:
top5 = users.sort_values(by='followers', ascending=False).head()
print(','.join(top5['login'].tolist()))

mosh-hamedani,TheCherno,haileys,rstacruz,jesseduffield

In [ ]:
users['created_at'] = pd.to_datetime(users['created_at'])

In [ ]:
top_earliest = users.sort_values(by='created_at').head()
print(','.join(top_earliest['login'].tolist()))

toolmantim,crafterm,dgoodlad,Sutto,mdub

In [ ]:
repos = pd.read_csv('repositories.csv')
repos.head()

,login,full_name,created_at,stargazers_count,watchers_count,language,has_projects,has_wiki,license_name
0,mosh-hamedani,mosh-hamedani/python-projects-for-beginners,2024-08-29T17:14:21Z,72,72,Python,True,False,NaN
1,mosh-hamedani,mosh-hamedani/vidly-mvc-5,2016-03-31T06:37:00Z,956,956,JavaScript,True,True,NaN
2,mosh-hamedani,mosh-hamedani/react-course-part2-starter,2023-04-17T12:37:33Z,63,63,TypeScript,True,True,NaN
3,mosh-hamedani,mosh-hamedani/python-supplementary-materials,2024-07-16T22:44:04Z,23,23,NaN,True,True,NaN
4,mosh-hamedani,mosh-hamedani/react-testing-starter,2024-01-29T20:30:40Z,60,60,TypeScript,True,False,NaN

In [ ]:
repos['license_name'].value_counts().head(3)

license_name
mit           8523
other         2472
apache-2.0    1839
Name: count, dtype: int64

In [ ]:
users['company'].value_counts().head(1)

company
MONASH UNIVERSITY    8
Name: count, dtype: int64

In [ ]:
repos['language'].value_counts().head(1)

language
JavaScript    5852
Name: count, dtype: int64

In [ ]:
users_after_2020 = users[users['created_at'] > '2020-01-01']
users_after_2020.head()

,login,name,company,location,email,hireable,bio,public_repos,followers,following,created_at
95,AndiiCodes,AndiiCodes,RMIT UNIVERSITY,"Melbourne, Australia",NaN,True,Jr. Front-End Dev,9,299,29,2022-10-26 23:50:19+00:00
179,feit-comp30023-2024,comp30023-2024,THE UNIVERSITY OF MELBOURNE,"Melbourne, Australia",NaN,False,Faculty of Engineering and Information Technol...,0,170,0,2024-02-26 04:25:41+00:00
186,rmit-computing-technologies,RMIT School of Computing Technologies,NaN,"Melbourne, Victoria",NaN,False,NaN,4,166,0,2021-04-06 13:20:48+00:00
213,NiREvil,Ransomware Evil,RAYAN EL,"Australia, Melbourne",NaN,False,phD EW,27,149,22,2023-02-24 09:57:18+00:00
226,nataliethenerd,NaN,NaN,"Melbourne, Australia",NaN,False,self taught baby programmer and maker\r\n\r\ns...,17,141,26,2021-02-20 05:30:10+00:00

In [ ]:
repos_2020 = repos[repos['login'].isin(users_after_2020['login'].tolist())]
repos_2020['language'].value_counts().head()

language
Python              37
JavaScript          32
Jupyter Notebook    29
HTML                 9
Astro                6
Name: count, dtype: int64

In [ ]:
avg_stars = repos.groupby('language')['stargazers_count'].mean()
top_lang = avg_stars.idxmax()
top_stars = avg_stars.max()
print(top_lang, top_stars)

D 2520.75

In [ ]:
users['leader_strength'] = users['followers'] / (1 + users['following'])
top5_lead = users.sort_values(by='leader_strength', ascending=False).head()
print(','.join(top5_lead['login'].tolist()))

mosh-hamedani,binarythistle,TheCherno,TuPayChain,rogerclarkmelbourne

In [ ]:
correlation = users['followers'].corr(users['public_repos'])
correlation

0.18933443837202274

In [ ]:
import csv
followers = []
public_repos = []
with open('users.csv', 'r', encoding='utf-8') as file:
    reader = csv.DictReader(file)
    for row in reader:
        followers_count = int(row['followers'])
        public_repos_count = int(row['public_repos'])
        followers.append(followers_count)
        public_repos.append(public_repos_count)
if len(followers) > 1 and len(public_repos) > 1:
    slope, intercept = np.polyfit(public_repos, followers, 1)

    print(f"{slope:.3f}")
else:
    print("Error")

2.257

In [ ]:
if repos['has_projects'].dtype == 'object':
    repos['has_projects'] = repos['has_projects'].map({'true': True, 'false': False})
if repos['has_wiki'].dtype == 'object':
    repos['has_wiki'] = repos['has_wiki'].map({'true': True, 'false': False})

correlation = repos['has_projects'].corr(repos['has_wiki'])

print(round(correlation, 3))

0.379

In [ ]:
hireable_avg_following = users[users['hireable'] == True]['following'].mean()
non_hireable_avg_following = users[users['hireable'] == False]['following'].mean()
difference = hireable_avg_following - non_hireable_avg_following
difference

-46.186069210292814

In [ ]:
from sklearn.linear_model import LinearRegression
users_with_bio = users[(users['bio'].notna()) & (users['bio'] != '')].copy()
users_with_bio.loc[:, 'bio_len'] = users_with_bio['bio'].str.len()

X = users_with_bio['bio_len'].values.reshape(-1,1)
y = users_with_bio['followers']

lr2 = LinearRegression()
lr2.fit(X, y)
lr2.coef_[0]

0.889210571506478

In [ ]:
import csv
from collections import Counter
from datetime import datetime

weekend_repo_counts = Counter()

with open('repositories.csv', 'r', encoding='utf-8') as file:
    reader = csv.DictReader(file)

    for row in reader:
        created_at = row.get('created_at', '')
        if created_at:
            created_date = datetime.fromisoformat(created_at[:-1])

            if created_date.weekday() in [5, 6]:
                user_login = row['login']
                weekend_repo_counts[user_login] += 1

top_users = weekend_repo_counts.most_common(5)

top_logins = [user[0] for user in top_users]

print(','.join(top_logins))

wolfeidau,karkranikhil,roachhd,plutext,rstacruz

In [ ]:
fraction_hierable = users[users['hireable'] == True]['email'].notna().mean()
fraction_non_hierable = users[users['hireable'] == False]['email'].notna().mean()
diff = fraction_hierable - fraction_non_hierable
diff

0.05647737355811888

In [ ]:
new_users = users[users['name'].notna()].copy()
new_users['surname'] = new_users['name'].str.split().str[-1].str.strip()
surname_counts = new_users['surname'].value_counts()
max_count = surname_counts.max()
common_surnames = surname_counts[surname_counts == max_count].index.tolist()
common_surnames.sort()
print(','.join(common_surnames))

Jackson,Wang

In [1]:
import pandas as pd
import statsmodels.api as sm

# Load the CSV file
csv_file = 'users.csv'  # Ensure this path is correct

# Load the CSV into a DataFrame
df = pd.read_csv(csv_file)

# Check the first few rows and the data types of the DataFrame
print("DataFrame Overview:")
print(df.head())
print("\nDataFrame Info:")
print(df.info())

# Filter out users without bios
df = df[df['bio'].notnull()]

# Calculate the length of each bio in words
df['bio_word_count'] = df['bio'].str.split().str.len()

# Prepare the independent variable (X) and dependent variable (y)
X = df['bio_word_count']
y = df['followers']  # Adjust the column name as per your dataset

# Add a constant to the independent variable (for the intercept)
X = sm.add_constant(X)

# Fit the regression model
model = sm.OLS(y, X).fit()

# Get the slope (coefficient of the bio_word_count)
slope = model.params['bio_word_count']

# Print the regression slope rounded to three decimal places
print(f"\nRegression slope of followers on bio word count: {slope:.3f}")

DataFrame Overview:
           login               name company              location  \
0  mosh-hamedani      Mosh Hamedani     NaN  Melbourne, Australia
1      TheCherno      Yan Chernikov     NaN  Melbourne, Australia
2        haileys  Hailey Somerville     NaN     Naarm / Melbourne
3       rstacruz     Rico Sta. Cruz     NaN         Melbourne, AU
4  jesseduffield     Jesse Duffield     NaN             Melbourne

                      email  hireable  \
0                       NaN     False
1                       NaN     False
2         hailey@hailey.lol     False
3                       NaN      True
4  jessedduffield@gmail.com     False

                                                 bio  public_repos  followers  \
0  I train software engineers that companies love...            27      12782
1                                                NaN            35      11229
2                                                NaN           372       9392
3                             @rstacruz@hachyderm.io           562       6434
4  Creator of lazygit, lazydocker, horcrux, and t...            60       4576

   following            created_at
0          1  2013-09-12T04:38:33Z
1          4  2012-02-26T08:39:00Z
2        104  2010-01-09T14:49:23Z
3         25  2009-04-16T09:46:24Z
4          4  2014-08-15T09:18:18Z

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337 entries, 0 to 336
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   login         337 non-null    object
 1   name          327 non-null    object
 2   company       190 non-null    object
 3   location      337 non-null    object
 4   email         151 non-null    object
 5   hireable      337 non-null    bool
 6   bio           208 non-null    object
 7   public_repos  337 non-null    int64
 8   followers     337 non-null    int64
 9   following     337 non-null    int64
 10  created_at    337 non-null    object
dtypes: bool(1), int64(3), object(7)
memory usage: 26.8+ KB
None

Regression slope of followers on bio word count: 7.709

<ipython-input-1-2d0cbe58dc40>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bio_word_count'] = df['bio'].str.split().str.len()

In [2]:
import csv
from collections import Counter

# Counter to store surname frequencies
surname_counter = Counter()

# Open the users.csv file and read data
with open('users.csv', 'r', encoding='utf-8') as file:
    reader = csv.DictReader(file)

    for row in reader:
        name = row.get('name', '').strip()
        if name:  # Ignore missing names
            # Split the name by whitespace and get the last word as the surname
            surname = name.split()[-1]
            surname_counter[surname] += 1

# Find the maximum frequency of surnames
if surname_counter:
    max_count = max(surname_counter.values())
    # Get all surnames with the maximum frequency
    most_common_surnames = [surname for surname, count in surname_counter.items() if count == max_count]
    # Sort surnames alphabetically
    most_common_surnames.sort()
    # Output the result
    print(f"{', '.join(most_common_surnames)}: {max_count}")
else:
    print("No names found.")

Jackson, Wang: 3